=== msr8/c/practicals/1/wt/q18/teacher.dtd
<!ELEMENT TeacherDetails (Name, Age, Salary, Subject, Course)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Age (#PCDATA)>
<!ELEMENT Salary (#PCDATA)>
<!ELEMENT Subject (#PCDATA)>
<!ELEMENT Course (#PCDATA)>

=== msr8/c/practicals/wt/q18/teacher.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE TeacherDetails SYSTEM "teacher.dtd">
<TeacherDetails>
    <Teacher>
        <Name>Rakesh Sharma</Name>
        <Age>45</Age>
        <Salary>80,000</Salary>
        <Subject>Mathematics</Subject>
        <Course>BCA</Course>
    </Teacher>

    <Teacher>
        <Name>Anjali Batra</Name>
        <Age>39</Age>
        <Salary>150,000</Salary>
        <Subject>Computer Science</Subject>
        <Course>B.Tech</Course>
    </Teacher>

    <Teacher>
        <Name>Mohan Kumar</Name>
        <Age>51</Age>
        <Salary>97,000</Salary>
        <Subject>Web Technology</Subject>
        <Course>BCA</Course>
    </Teacher>
</TeacherDetails>
